name: CI/CD

on:
  push:
    branches:
      - main

jobs:

  push_frames:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: pip install pymongo

      - name: Push frames to MongoDB Atlas
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
        run: python mongodb.py
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Choose your Python version

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run Python tests
      run: |
        python -m unittest discover -s ./Backend/app/tests -p 'test_*.py'

    - name: Build
      run: npm run build

    - name: Deploy
      # Add your deployment script here
      run: |
        echo "Deploying..."
